POST http://localhost:3000/api/users
Content-Type: application/json

{
    "email":"email02@gmail.com",
    "role": "medic"
    
}

###
GET http://localhost:3000/api/users

###
GET http://localhost:3000/api/users/1ebe6aeb-fbd6-4743-9c18-ba9764171012

###
PUT http://localhost:3000/api/users/1ebe6aeb-fbd6-4743-9c18-ba9764171012
Content-Type: application/json

{
    "email":"email02UPD@gmail.com",
    "role": "medic",
    "relatedId": "gertgg43546"
}

###
DELETE http://localhost:3000/api/users/6ec2a378-8b09-4162-8b4a-8de8710ba811